development:
  adapter: postgresql
  encoding: utf8
  database: cash
  host: localhost
  pool: 5
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  database: grubguroo_test
  pool: 5
