development:
  adapter: postgresql
  encoding: unicode
  database: cash
  pool: 5
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: cash
  pool: 5
